//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo2_mp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Admin
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "UserName không được rỗng")]
        [Display(Name = "UserName")]

        public string NameUser { get; set; }
        [Required(ErrorMessage = "Password không được rỗng")]
        [Display(Name = "Password")]


        public string PasswordUser { get; set; }

        public string FullName { get; set; }
    }
}
