//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo2_mp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProductID { get; set; }
        [Required(ErrorMessage = "Tên sản phẩm không được rỗng")]
        [Display(Name = "Tên sản phẩm")]


        public string NamePro { get; set; }
        public string DecriptionPro { get; set; }
        public string ShortDec { get; set; }
        public Nullable<int> Category { get; set; }
        [Required(ErrorMessage = "Giá không được rỗng")]
        [Display(Name = "Giá")]

        public Nullable<double> Price { get; set; }
        [Required(ErrorMessage = "Hình ảnh không được rỗng")]
        [Display(Name = "File hình")]
        public string ImagePro { get; set; }
        [Required(ErrorMessage = "Hình ảnh không được rỗng")]
        [Display(Name = "File hình")]
        public string Image1 { get; set; }
        [Required(ErrorMessage = "Hình ảnh không được rỗng")]
        [Display(Name = "File hình")]
        public string Image2 { get; set; }
        [Required(ErrorMessage = "Hình ảnh không được rỗng")]
        [Display(Name = "File hình")]
        public Nullable<double> DungLuong { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
